project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!files/"
    - "!ingest/"

website:
  title: "Data viz. in R {{< fa rainbow >}}"
  favicon: html/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: slides_grid.qmd
        text: "Slides {{< fa-brands fa-slideshare >}}"
    right:
      - href: pipeline/00-planning.qmd
        text: "Planning {{< fa ruler >}}"

format:
  html:
    theme:
      - flatly
      - html/custom.scss
    css: html/styles.css
    toc: true

execute:
  freeze: auto